import { ItemData } from '../typings/item';

export const Items: {
  [key: string]: ItemData | undefined;
} = {
  iron: {
    name: 'iron',
    close: false,
    label: 'Iron',
    stack: true,
    usable: false,
    count: 0,
  },
  copper: {
    name: 'copper',
    close: false,
    label: 'Copper',
    stack: true,
    usable: false,
    count: 0,
  },
  water: {
    name: 'water',
    close: false,
    label: 'Water',
    stack: true,
    usable: true,
    count: 0,
  },
  burger: {
    name: 'burger',
    close: false,
    label: 'Burger',
    stack: false,
    usable: false,
    count: 0,
  },
  energy_junk1: {
    name: 'energy_junk1',
    close: false,
    label: 'Energy Drink',
    stack: false,
    usable: true,
    count: 0,
  },
  weapon_pistol: {
    name: 'weapon_pistol',
    close: false,
    label: 'Pistol',
    stack: false,
    usable: true,
    count: 0,
  },
  weapon_combatpistol: {
    name: 'weapon_combatpistol',
    close: false,
    label: 'Combat Pistol',
    stack: false,
    usable: true,
    count: 0,
  },
  lockpick: {
    name: 'lockpick',
    close: false,
    label: 'Lockpick',
    stack: false,
    usable: true,
    count: 0,
  },
  weapon_carbinerifle: {
    name: 'weapon_carbinerifle',
    close: false,
    label: 'Carbine Rifle',
    stack: false,
    usable: true,
    count: 0,
  },
  weapon_assaultrifle: {
    name: 'weapon_assaultrifle',
    close: false,
    label: 'Assault Rifle',
    stack: false,
    usable: true,
    count: 0,
  },
};
